---
- name: Provision EC2 instance
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create EC2 instance
      ec2:
        key_name: "{{ key_pair }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_id }}"
        region: "{{ aws_region }}"
        group: "{{ security_group }}"
        vpc_subnet_id: "{{ subnet_id }}"
        assign_public_ip: yes
        wait: yes
      register: ec2_instance

    - name: Add EC2 instance to AWX inventory
      add_host:
        name: "{{ ec2_instance.instances[0].public_ip }}"
        groups: "ec2_instances"
        ansible_ssh_private_key_file: "{{ private_key_file }}"
        ansible_user: "{{ ansible_user }}"
